//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTI.Modules.PlayerCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTI.Modules.PlayerCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;ctivate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add the player to the server. Reason: {0}.
        /// </summary>
        internal static string AddPlayerFailed {
            get {
                return ResourceManager.GetString("AddPlayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        internal static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArDn50x42DN {
            get {
                object obj = ResourceManager.GetObject("ArDn50x42DN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArDn50x42UP {
            get {
                object obj = ResourceManager.GetObject("ArDn50x42UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrDN32 {
            get {
                object obj = ResourceManager.GetObject("ArrDN32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDownRed {
            get {
                object obj = ResourceManager.GetObject("ArrowDownRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUpRed {
            get {
                object obj = ResourceManager.GetObject("ArrowUpRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrUP32 {
            get {
                object obj = ResourceManager.GetObject("ArrUP32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArUp50x42DN {
            get {
                object obj = ResourceManager.GetObject("ArUp50x42DN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArUp50x42UP {
            get {
                object obj = ResourceManager.GetObject("ArUp50x42UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Spend.
        /// </summary>
        internal static string AverageSpend {
            get {
                return ResourceManager.GetString("AverageSpend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG00 {
            get {
                object obj = ResourceManager.GetObject("BG00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonDown {
            get {
                object obj = ResourceManager.GetObject("BlueButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonUp {
            get {
                object obj = ResourceManager.GetObject("BlueButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to record the attendance of the player.
        ///
        ///Reason: {0}.
        /// </summary>
        internal static string CardSwipeFailed {
            get {
                return ResourceManager.GetString("CardSwipeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard the changes you have made?.
        /// </summary>
        internal static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clear the player Raffle on the server. Reason: {0}.
        /// </summary>
        internal static string ClearPlayerRaffle {
            get {
                return ResourceManager.GetString("ClearPlayerRaffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to create a new account?.
        /// </summary>
        internal static string CreatePlayer {
            get {
                return ResourceManager.GetString("CreatePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to created the player. Reason: {0}.
        /// </summary>
        internal static string CreatePlayerFailed {
            get {
                return ResourceManager.GetString("CreatePlayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Raffle Winner!.
        /// </summary>
        internal static string CurrentRaffleWinner {
            get {
                return ResourceManager.GetString("CurrentRaffleWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than.
        /// </summary>
        internal static string DayPlayedOption1 {
            get {
                return ResourceManager.GetString("DayPlayedOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than or Equal .
        /// </summary>
        internal static string DayPlayedOption2 {
            get {
                return ResourceManager.GetString("DayPlayedOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        internal static string DayPlayedOption3 {
            get {
                return ResourceManager.GetString("DayPlayedOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than Or Equal .
        /// </summary>
        internal static string DayPlayedOption4 {
            get {
                return ResourceManager.GetString("DayPlayedOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        internal static string DayPlayedOption5 {
            get {
                return ResourceManager.GetString("DayPlayedOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dea&amp;ctivate.
        /// </summary>
        internal static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Player Card PIN.
        /// </summary>
        internal static string EnterPlayerCardPIN {
            get {
                return ResourceManager.GetString("EnterPlayerCardPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed. Mag card already assigned. .
        /// </summary>
        internal static string errorDupMagCard {
            get {
                return ResourceManager.GetString("errorDupMagCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to take picture, please verify camera is installed properly..
        /// </summary>
        internal static string errorFailedToTakePicture {
            get {
                return ResourceManager.GetString("errorFailedToTakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN, Numbers ONLY..
        /// </summary>
        internal static string errorInvalidPIN {
            get {
                return ResourceManager.GetString("errorInvalidPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN, Verify PIN DOES NOT match original..
        /// </summary>
        internal static string errorPINMatch {
            get {
                return ResourceManager.GetString("errorPINMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string ExportSeparator {
            get {
                return ResourceManager.GetString("ExportSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindPlayerBack1024 {
            get {
                object obj = ResourceManager.GetObject("FindPlayerBack1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindPlayerBack800 {
            get {
                object obj = ResourceManager.GetObject("FindPlayerBack800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindPlayerBack800b {
            get {
                object obj = ResourceManager.GetObject("FindPlayerBack800b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindPlayerBack800c {
            get {
                object obj = ResourceManager.GetObject("FindPlayerBack800c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindPlayerBack800d {
            get {
                object obj = ResourceManager.GetObject("FindPlayerBack800d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No player is selected..
        /// </summary>
        internal static string FindPlayerFormNoPlayer {
            get {
                return ResourceManager.GetString("FindPlayerFormNoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string GenderOther {
            get {
                return ResourceManager.GetString("GenderOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the device and/or machine id.  Reason: {0}.
        /// </summary>
        internal static string GetDeviceInfoFailed {
            get {
                return ResourceManager.GetString("GetDeviceInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the last Raffle winner from the server.  Reason: {0}.
        /// </summary>
        internal static string GetLastPlayerRaffleWinner {
            get {
                return ResourceManager.GetString("GetLastPlayerRaffleWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the machine&apos;s information from the server.
        ///
        ///Reason: {0}.
        /// </summary>
        internal static string GetMachineFailed {
            get {
                return ResourceManager.GetString("GetMachineFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the player comps information from the server. Reason: {0}.
        /// </summary>
        internal static string GetPlayerCompsFailed {
            get {
                return ResourceManager.GetString("GetPlayerCompsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the player from the server.  Reason: {0}.
        /// </summary>
        internal static string GetPlayerFailed {
            get {
                return ResourceManager.GetString("GetPlayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the player(s) from the server.  Reason: {0}.
        /// </summary>
        internal static string GetPlayerListFailed {
            get {
                return ResourceManager.GetString("GetPlayerListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the player tier information from the server. Reason: {0}.
        /// </summary>
        internal static string GetPlayerTiersFailed {
            get {
                return ResourceManager.GetString("GetPlayerTiersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the report from the server. Reason: {0}.
        /// </summary>
        internal static string GetReportFailed {
            get {
                return ResourceManager.GetString("GetReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get this workstation&apos;s settings from the server.  Reason: {0}.
        /// </summary>
        internal static string GetSettingsFailed {
            get {
                return ResourceManager.GetString("GetSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Issued Id Number.
        /// </summary>
        internal static string GovIssuedIdNum {
            get {
                return ResourceManager.GetString("GovIssuedIdNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player not found..
        /// </summary>
        internal static string InfoPlayerNotFound {
            get {
                return ResourceManager.GetString("InfoPlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Award Points.
        /// </summary>
        internal static string InfoPointsAwardFailed {
            get {
                return ResourceManager.GetString("InfoPointsAwardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points successfully adjusted..
        /// </summary>
        internal static string InfoPointsAwardSuccessed {
            get {
                return ResourceManager.GetString("InfoPointsAwardSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Data Successfully..
        /// </summary>
        internal static string InfoSaveSuccessed {
            get {
                return ResourceManager.GetString("InfoSaveSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid birthday!.
        /// </summary>
        internal static string InvalidBirthDate {
            get {
                return ResourceManager.GetString("InvalidBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} response received from server..
        /// </summary>
        internal static string InvalidMessageResponse {
            get {
                return ResourceManager.GetString("InvalidMessageResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday must be a valid date range!.
        /// </summary>
        internal static string InvalidPlayerListBirthday {
            get {
                return ResourceManager.GetString("InvalidPlayerListBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From birthday must be before To birthday!.
        /// </summary>
        internal static string InvalidPlayerListBirthdayBackward {
            get {
                return ResourceManager.GetString("InvalidPlayerListBirthdayBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From last visit must be before To last visit!.
        /// </summary>
        internal static string InvalidPlayerListLastVisit {
            get {
                return ResourceManager.GetString("InvalidPlayerListLastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date must be less than to date!.
        /// </summary>
        internal static string InvalidPlayerListNDaysPlayedDateRange {
            get {
                return ResourceManager.GetString("InvalidPlayerListNDaysPlayedDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option!.
        /// </summary>
        internal static string InvalidPlayerListNDaysPlayedOptionSElected {
            get {
                return ResourceManager.GetString("InvalidPlayerListNDaysPlayedOptionSElected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be 0 or empty!.
        /// </summary>
        internal static string InvalidPlayerListNDaysPlayedOptionSelectedValue {
            get {
                return ResourceManager.GetString("InvalidPlayerListNDaysPlayedOptionSelectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From range must be less than or equal to To range!.
        /// </summary>
        internal static string InvalidPlayerListNDaysPlayedRange {
            get {
                return ResourceManager.GetString("InvalidPlayerListNDaysPlayedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range must be a valid number range!.
        /// </summary>
        internal static string InvalidPlayerListNDaysPlayedRange2 {
            get {
                return ResourceManager.GetString("InvalidPlayerListNDaysPlayedRange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date must be less than to date!.
        /// </summary>
        internal static string InvalidPlayerListNSessionPlayedDateRange {
            get {
                return ResourceManager.GetString("InvalidPlayerListNSessionPlayedDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option!.
        /// </summary>
        internal static string InvalidPlayerListNSessionPlayedOptionSelected {
            get {
                return ResourceManager.GetString("InvalidPlayerListNSessionPlayedOptionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be 0 or empty!.
        /// </summary>
        internal static string InvalidPlayerListNSessionPlayedOptionSelectedValue {
            get {
                return ResourceManager.GetString("InvalidPlayerListNSessionPlayedOptionSelectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From range must be less than or equal to To range!.
        /// </summary>
        internal static string InvalidPlayerListNSessionPlayedRange {
            get {
                return ResourceManager.GetString("InvalidPlayerListNSessionPlayedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range must be a valid number range!.
        /// </summary>
        internal static string InvalidPlayerListNSessionPlayedRange2 {
            get {
                return ResourceManager.GetString("InvalidPlayerListNSessionPlayedRange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point balance must be a valid number range!.
        /// </summary>
        internal static string InvalidPlayerListPoints {
            get {
                return ResourceManager.GetString("InvalidPlayerListPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. points must be less than or equal to Max. points!.
        /// </summary>
        internal static string InvalidPlayerListPointsBackward {
            get {
                return ResourceManager.GetString("InvalidPlayerListPointsBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spend must be a valid number range!.
        /// </summary>
        internal static string InvalidPlayerListSpend {
            get {
                return ResourceManager.GetString("InvalidPlayerListSpend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From spend must be less than or equal to To spend!.
        /// </summary>
        internal static string InvalidPlayerListSpendBackward {
            get {
                return ResourceManager.GetString("InvalidPlayerListSpendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From spend date must be before To spend date!.
        /// </summary>
        internal static string InvalidPlayerListSpendDateBackward {
            get {
                return ResourceManager.GetString("InvalidPlayerListSpendDateBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a status..
        /// </summary>
        internal static string InvalidPlayerListStatus {
            get {
                return ResourceManager.GetString("InvalidPlayerListStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid setting {0}. Value: {1}..
        /// </summary>
        internal static string InvalidSetting {
            get {
                return ResourceManager.GetString("InvalidSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date.
        /// </summary>
        internal static string JoinDate {
            get {
                return ResourceManager.GetString("JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Raffle Winner..
        /// </summary>
        internal static string LastRaffleWinner {
            get {
                return ResourceManager.GetString("LastRaffleWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Visit.
        /// </summary>
        internal static string LastVisit {
            get {
                return ResourceManager.GetString("LastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoadingBack1024 {
            get {
                object obj = ResourceManager.GetObject("LoadingBack1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoadingBack800 {
            get {
                object obj = ResourceManager.GetObject("LoadingBack800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving player loyalty tiers..
        /// </summary>
        internal static string LoadingPlayerTiers {
            get {
                return ResourceManager.GetString("LoadingPlayerTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Status Code....
        /// </summary>
        internal static string LoadingStatusCode {
            get {
                return ResourceManager.GetString("LoadingStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving this workstation&apos;s settings..
        /// </summary>
        internal static string LoadingWorkstationInfo {
            get {
                return ResourceManager.GetString("LoadingWorkstationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load player picture.  Reason: {0}.
        /// </summary>
        internal static string LoadPictureFailed {
            get {
                return ResourceManager.GetString("LoadPictureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the log. Reason: {0}.
        /// </summary>
        internal static string LogFailed {
            get {
                return ResourceManager.GetString("LogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MagCardBack {
            get {
                object obj = ResourceManager.GetObject("MagCardBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetic Card Number.
        /// </summary>
        internal static string MagCardNumber {
            get {
                return ResourceManager.GetString("MagCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the magnetic card reader. Reason: {0}.
        /// </summary>
        internal static string MagLoadError {
            get {
                return ResourceManager.GetString("MagLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}.
        /// </summary>
        internal static string MessageName {
            get {
                return ResourceManager.GetString("MessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} message payload size is too small..
        /// </summary>
        internal static string MessagePayloadTooSmall {
            get {
                return ResourceManager.GetString("MessagePayloadTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} message payload is the wrong size..
        /// </summary>
        internal static string MessagePayloadWrongSize {
            get {
                return ResourceManager.GetString("MessagePayloadWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Initial.
        /// </summary>
        internal static string MiddleInitial {
            get {
                return ResourceManager.GetString("MiddleInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add, Edit and Delete player data such as membership, game play and rewards info..
        /// </summary>
        internal static string ModuleDescription {
            get {
                return ResourceManager.GetString("ModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player must have a last name or mag. card # before saving!.
        /// </summary>
        internal static string NoNameOrCard {
            get {
                return ResourceManager.GetString("NoNameOrCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-refundable Credit.
        /// </summary>
        internal static string NonRefundableCredit {
            get {
                return ResourceManager.GetString("NonRefundableCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoPic {
            get {
                object obj = ResourceManager.GetObject("NoPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot sell to a blank player..
        /// </summary>
        internal static string NoPlayer {
            get {
                return ResourceManager.GetString("NoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No players matched the criteria you specified..
        /// </summary>
        internal static string NoPlayersExported {
            get {
                return ResourceManager.GetString("NoPlayersExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No player found for that card..
        /// </summary>
        internal static string NoPlayersFound {
            get {
                return ResourceManager.GetString("NoPlayersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough players for a Raffle..
        /// </summary>
        internal static string NoRafflePlayers {
            get {
                return ResourceManager.GetString("NoRafflePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN must be {0} digits.
        /// </summary>
        internal static string PinMustBeSetLengthText {
            get {
                return ResourceManager.GetString("PinMustBeSetLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN is required..
        /// </summary>
        internal static string PinRequired {
            get {
                return ResourceManager.GetString("PinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PINs do not match.
        /// </summary>
        internal static string PinsDoNotMatchText {
            get {
                return ResourceManager.GetString("PinsDoNotMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player card PIN entry canceled.
        /// </summary>
        internal static string PlayerCardPINEntryCanceled {
            get {
                return ResourceManager.GetString("PlayerCardPINEntryCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect PIN..
        /// </summary>
        internal static string PlayerCardPINError {
            get {
                return ResourceManager.GetString("PlayerCardPINError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. The Player Center module will now shutdown. Error: {0}.
        /// </summary>
        internal static string PlayerCenterError {
            get {
                return ResourceManager.GetString("PlayerCenterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Center.
        /// </summary>
        internal static string PlayerCenterName {
            get {
                return ResourceManager.GetString("PlayerCenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Id.
        /// </summary>
        internal static string PlayerId {
            get {
                return ResourceManager.GetString("PlayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Identity.
        /// </summary>
        internal static string PlayerIdentity {
            get {
                return ResourceManager.GetString("PlayerIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerMgmtBack800 {
            get {
                object obj = ResourceManager.GetObject("PlayerMgmtBack800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Players {
            get {
                object obj = ResourceManager.GetObject("Players", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerScreen1024 {
            get {
                object obj = ResourceManager.GetObject("PlayerScreen1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerScreen10241 {
            get {
                object obj = ResourceManager.GetObject("PlayerScreen10241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerScreenCredits1024 {
            get {
                object obj = ResourceManager.GetObject("PlayerScreenCredits1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set the player. Reason: {0}.
        /// </summary>
        internal static string PlayerSetFailed {
            get {
                return ResourceManager.GetString("PlayerSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} players exported..
        /// </summary>
        internal static string PlayersExported {
            get {
                return ResourceManager.GetString("PlayersExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} player(s) were awarded points..
        /// </summary>
        internal static string PlayersRewarded {
            get {
                return ResourceManager.GetString("PlayersRewarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Player Tracking Interface is down..
        /// </summary>
        internal static string PlayerTrackingInterfaceDown {
            get {
                return ResourceManager.GetString("PlayerTrackingInterfaceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Balance.
        /// </summary>
        internal static string PointsBalance {
            get {
                return ResourceManager.GetString("PointsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Center.
        /// </summary>
        internal static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raffle.
        /// </summary>
        internal static string RaffleButtonText {
            get {
                return ResourceManager.GetString("RaffleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raffle in progress, please wait for previous raffle to end..
        /// </summary>
        internal static string RaffleInProgress {
            get {
                return ResourceManager.GetString("RaffleInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Raffle has not been started..
        /// </summary>
        internal static string RaffleNotStarted {
            get {
                return ResourceManager.GetString("RaffleNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refundable Credit.
        /// </summary>
        internal static string RefundableCredit {
            get {
                return ResourceManager.GetString("RefundableCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reset50x42DN {
            get {
                object obj = ResourceManager.GetObject("Reset50x42DN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reset50x42UP {
            get {
                object obj = ResourceManager.GetObject("Reset50x42UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run the player Raffle on the server. Reason: {0}.
        /// </summary>
        internal static string RunPlayerRaffle {
            get {
                return ResourceManager.GetString("RunPlayerRaffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save player picture.  Reason: {0}.
        /// </summary>
        internal static string SavePictureFailed {
            get {
                return ResourceManager.GetString("SavePictureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the player to the server.  Reason: {0}.
        /// </summary>
        internal static string SavePlayerFailed {
            get {
                return ResourceManager.GetString("SavePlayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server communication lost..
        /// </summary>
        internal static string ServerCommFailed {
            get {
                return ResourceManager.GetString("ServerCommFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned error code: {0}.
        /// </summary>
        internal static string ServerErrorCode {
            get {
                return ResourceManager.GetString("ServerErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down....
        /// </summary>
        internal static string ShuttingDown {
            get {
                return ResourceManager.GetString("ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SpacebarDown {
            get {
                object obj = ResourceManager.GetObject("SpacebarDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SpacebarUp {
            get {
                object obj = ResourceManager.GetObject("SpacebarUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Player Center....
        /// </summary>
        internal static string StartingPlayerCenter {
            get {
                return ResourceManager.GetString("StartingPlayerCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status List.
        /// </summary>
        internal static string StatusList {
            get {
                return ResourceManager.GetString("StatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Spend.
        /// </summary>
        internal static string TotalSpend {
            get {
                return ResourceManager.GetString("TotalSpend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TouchBlueButtonDown {
            get {
                object obj = ResourceManager.GetObject("TouchBlueButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TouchBlueButtonUp {
            get {
                object obj = ResourceManager.GetObject("TouchBlueButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unnamed entries remaining, please name them..
        /// </summary>
        internal static string UnnamedStatusEntries {
            get {
                return ResourceManager.GetString("UnnamedStatusEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ViewRaffleWinnerBack {
            get {
                object obj = ResourceManager.GetObject("ViewRaffleWinnerBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Count.
        /// </summary>
        internal static string VisitCount {
            get {
                return ResourceManager.GetString("VisitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awarding points to {0} players, please wait..
        /// </summary>
        internal static string WaitFormAwardingToAGroupOfPlayer {
            get {
                return ResourceManager.GetString("WaitFormAwardingToAGroupOfPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awarding points to player list, please wait..
        /// </summary>
        internal static string WaitFormAwardPoints {
            get {
                return ResourceManager.GetString("WaitFormAwardPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting list, please wait..
        /// </summary>
        internal static string WaitFormExportingList {
            get {
                return ResourceManager.GetString("WaitFormExportingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for players, please wait..
        /// </summary>
        internal static string WaitFormFindingPlayers {
            get {
                return ResourceManager.GetString("WaitFormFindingPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting machine data, please wait..
        /// </summary>
        internal static string WaitFormGettingMachine {
            get {
                return ResourceManager.GetString("WaitFormGettingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting player data, please wait..
        /// </summary>
        internal static string WaitFormGettingPlayer {
            get {
                return ResourceManager.GetString("WaitFormGettingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating player report, please wait..
        /// </summary>
        internal static string WaitFormGettingReport {
            get {
                return ResourceManager.GetString("WaitFormGettingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing player receipts, please wait..
        /// </summary>
        internal static string WaitFormPrintingPlayerRaffle {
            get {
                return ResourceManager.GetString("WaitFormPrintingPlayerRaffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing {0} player receipts, please wait..
        /// </summary>
        internal static string WaitFormPrintingPlayerRaffle2 {
            get {
                return ResourceManager.GetString("WaitFormPrintingPlayerRaffle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving player, please wait..
        /// </summary>
        internal static string WaitFormSavingPlayer {
            get {
                return ResourceManager.GetString("WaitFormSavingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating player information, please wait..
        /// </summary>
        internal static string WaitFormUpdatingPlayer {
            get {
                return ResourceManager.GetString("WaitFormUpdatingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Waiting {
            get {
                object obj = ResourceManager.GetObject("Waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN does not match..
        /// </summary>
        internal static string waringVerifiedPIN {
            get {
                return ResourceManager.GetString("waringVerifiedPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date must be greater than 1/1/1900..
        /// </summary>
        internal static string warningBirthDate {
            get {
                return ResourceManager.GetString("warningBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the wrong size..
        /// </summary>
        internal static string WrongSize {
            get {
                return ResourceManager.GetString("WrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
